[package]
authors = ["Paul Henschel", "chriscerie"]
description = "A modern spring-physics based animation library for Roact inspired by react-spring"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]
license = "MIT"
name = "howmanysmall/react-spring"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "3.0.0"

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@^1"
Promise = "howmanysmall/typed-promise@^4"
React = "jsdotlua/react@^17"
ReactRoblox = "jsdotlua/react-roblox@^17"
Signal = "howmanysmall/better-signal@2.1.0"
